title: Adios Internet Explore 
author: Hae-Jin LIM 
email: hae-jin.lim@inetum.com
description: > Bye Bye Internet Explore 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Hae-Jin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
